### ISSUE TITLE
Email and Phone nudge - Vietnamese 

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#993] opened 2021-07-14 19:01 UTC
## User story:
Email and Phone nudge in Vietnamese Language.  As a public user I should be able to view the same Email and Phone nudge in Vietnamese Language.

Refer to the following link for details and acceptance criteria.
Ref: https://github.com/usdoj-crt/crt-portal-management/issues/982

**Comment by randyabramson** [comment] 2021-07-27 01:06
@billyhunt  translation here:

[Vietnamese - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881946/Vietnamese.-.translation.-.FINAL.docx)

**Comment by blaughman** [comment] 2021-08-09 16:33
Function works as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-08-10 13:28
Works as intended. Moving to Staging.

**Comment by blaughman** [comment] 2021-08-11 15:58
Verified in Production.  Closing this card.

**Closed by blaughman** 2021-08-11 15:58 UTC
