### ISSUE TITLE
Move summary column to drop down carrot view

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#961] opened 2021-05-27 12:10 UTC
## User story:
As an Intake Specialist, I want to be be able to see the Summary content in the carrot drop down menu so I can efficiently assess reports

## Objective:
Move summary information out of the top columns in order to make room for ID and Location Name columns. We hope this new lineup of columns makes for a fuller list of relevant information in the View All table.

## Key result:
Positive feedback from Intake Specialists

## Ticket background:
We're iterating on the View All Table based on new needs and feedback from the Intake Specialists. Intake Specialists didn't find value in having it as one of the main columns in the View All Table.

## Acceptance criteria:
1. Given that I'm on the View All Table
When I click the carrot button
Then I see a drop down window that lists the Summary detail

2. Given that I'm on the View All Table
When I click the carrot button a second time
Then I see the drop down window retracts
 
## Assumption:
Per Aviva's mock, we will clear out CONTACT, LOCATION NAME and COMPLAINT ID from the carrot drop down and replace it with SUMMARY and PERSONAL DESCRIPTION

**Comment by randyabramson** [comment] 2021-05-27 14:12
<img width="646" alt="May 2021 updates" src="https://user-images.githubusercontent.com/6254621/119841625-f869eb00-bed3-11eb-93a1-a7d36d29eda1.PNG">

**Comment by randyabramson** [comment] 2021-05-28 10:40
Comments from Aviva on padding, etc.

* Right now the column header font is 16px, I think they can be 12px and will still be very legible being all caps
* I would try making the padding inside the cells just 10px between the content and the edge of the cell on all sides
* Try reducing the vertical space between the table and the filters/tags (in my mockup I think its only like 40 or 48px)

**Comment by randyabramson** [comment] 2021-06-02 19:55
<img width="639" alt="carrot-drawer-open-highlight" src="https://user-images.githubusercontent.com/6254621/120543997-eea42400-c3ba-11eb-9c56-374695b3cb08.PNG">

**Comment by blaughman** [comment] 2021-06-25 13:35
Function appears to work as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-06-26 01:21
Works as expected on STAGING

**Comment by randyabramson** [comment] 2021-06-29 21:20
Works as expected on PROD in CHROME and EDGE. Moving to closed

**Closed** 2021-07-28 15:54 UTC
