### ISSUE TITLE
Update Touchpoints module

### ISSUE THREAD

**Issue by chinelo-ikejimba** [usdoj-crt/crt-portal-management#1326] opened 2022-06-27 21:04 UTC
```
<script src="https://touchpoints.app.cloud.gov/touchpoints/6f09f3b6.js" async></script>
```

Touchpoints recruitment module to be updated in the CRT code.

**Comment by billyhunt** [comment] 2022-06-29 14:37
@chinelo-ikejimba @randyabramson @blaughman @ilodidoj are we ready to launch this into dev?

**Comment by blaughman** [comment] 2022-07-05 16:04
@billyhunt @ilodidoj @eileen-nava @chinelo-ikejimba @randyabramson Should the privacy policy URL be a clickable link?

<img width="281" alt="image" src="https://user-images.githubusercontent.com/52507395/177370147-56910c78-d857-4e82-b0ad-e3ccdc0de8d5.png">

**Comment by chinelo-ikejimba** [comment] 2022-07-05 16:20
> @billyhunt @ilodidoj @eileen-nava @chinelo-ikejimba @randyabramson Should the privacy policy URL be a clickable link?
> 
> <img alt="image" width="281" src="https://user-images.githubusercontent.com/52507395/177370147-56910c78-d857-4e82-b0ad-e3ccdc0de8d5.png">

@blaughman, we tried but the Touchpoints template doesn't allow for clickable hyperlinks. This was the best option it allowed.

**Comment by blaughman** [comment] 2022-07-05 16:42
Based upon the feedback, this functions and appears as intended.  Moving to UAT.

**Comment by blaughman** [comment] 2022-07-20 17:25
Appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2022-07-27 15:03
Can't test this in Production without creating a bad record.  Since this works in Staging, closing this card.

**Closed by blaughman** 2022-07-27 15:03 UTC
