### ISSUE TITLE
Enable users to customize how many reports display on /form/view

### ISSUE THREAD

**Issue by eileen-nava** [usdoj-crt/crt-portal-management#1281] opened 2022-05-16 17:03 UTC
## User story:
As an intake specialist, I need to be able to customize how many reports display on the `/form/view` page.

## Objective:
Make it easier for intake specialists to deal with frequent flier reports by enabling them to mass-select certain numbers of reports (15, 20, 50, etc.).

## Key result:
- No current metrics for this ticket.

## Ticket background:
A new frequent flier is submitting a high number of reports, and it would be easier for intake specialists to process the reports if they could customize how many reports they view on `/form/view`.

## Acceptance criteria:
- [ ] User can still view the `/form/view` without customizing how many reports to view
       - Log in as an intake specialist and navigate to `/form/view`
       - Confirm that you still see the default number of reports, 15
- [ ] User can customize how many reports they view
       - Log in as an intake specialist and navigate to `/form/view`
       - Select a certain number of reports, eg 50
       - Confirm that 50 reports display

## Open questions / Parts of this ticket that are still in the works
I am still in touch with @chinelo-ikejimba about what the ticket's front-end implementation will look like.  Users could select the number of records to display via a drop-down field or text field.  For now, I am focused on the back-end implementation.  Chinelo proposed the below as inspiration for the front-end implementation.

<img width="307" alt="show more messages selections" src="https://user-images.githubusercontent.com/80347702/168645576-c06786e9-7d48-485a-8e3e-a3c7e6926756.png">

**Comment by billyhunt** [comment] 2022-07-15 16:27
There could be some performance issues to consider here.  We probably want to have an upper limit.

**Comment by eileen-nava** [comment] 2022-07-15 20:00
@chinelo-ikejimba Thanks, Chinelo! 🙏🏻 
@billyhunt I will keep performance issues in mind as I start working on this.  I agree that an upper limit would be smart.

**Comment by chinelo-ikejimba** [comment] 2022-07-18 18:15
@billyhunt @eileen-nava @blaughman 

How about running a speed test to find out what number drastically slows down performance and/or load time? We could use that number as the upper limit.

**Comment by eileen-nava** [comment] 2022-07-18 21:02
Hi, here's a status update before the end of the day.  

I've been testing page load times this afternoon, with the goal of keeping load time below 1 second.  I noticed a slow-down at 200 records per page, when the page took ~0.903 seconds to load.  I haven't yet tested for mobile CPUs, but I am confident those would require more than ~0.903 seconds to load.

I'll report back after I test for mobile CPUs.

**Comment by chinelo-ikejimba** [comment] 2022-07-19 18:57
Thanks for the progress update @eileen-nava! 

Sounds like 200 might be the upper limit so far but we'll see how it goes with once you're done.

**Comment by blaughman** [comment] 2022-07-19 19:10
Cap the max number at 100

**Comment by chinelo-ikejimba** [comment] 2022-07-22 14:01
@eileen-nava (cc @blaughman @randyabramson @ilodidoj @billyhunt @JackRyan1989)

Due to tech constraints, let's provide a dropdown that's launched from a kabob menu placed next to the total records show text.

[Design handoff](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Reporting-Portal-Designs-and-Handoff?node-id=1202%3A10035)

**Collapsed kabob menu**
![View all table - functionality - kabob menu - collapsed](https://user-images.githubusercontent.com/92807659/180454164-8784808c-ae4f-45c8-b9e1-b5b22d829a57.png)

---


**Expanded kabob menu**
![View all table - functionality - kabob menu - expanded](https://user-images.githubusercontent.com/92807659/180454212-f67447a1-caa5-4848-8ec8-b8d8cbc6ffc9.png)

**Comment by randyabramson** [comment] 2022-07-25 16:06
7/25 update - @eileen-nava  starting development today

**Comment by blaughman** [comment] 2022-08-10 16:39
Functions as intended.  Holding off on final approval until Terri tests for accessibility.

**Comment by blaughman** [comment] 2022-08-17 12:04
Functions as intended in Production.  Closing this card.

**Closed by blaughman** 2022-08-17 12:04 UTC
