### ISSUE TITLE
Intake search filters: sort active filters 

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1035] opened 2021-08-24 19:01 UTC
## Summary

As originally noted in https://github.com/usdoj-crt/crt-portal-management/issues/1011

> All the filters are working as expected.  One issue I found was the 'Primary Issue' filter tiles populate to the left of the status tiles.  On all other filters, the tiles appear to the right of the status tiles. @randyabramson @louh @billyhunt @ilodidoj 
>
> ![image](https://user-images.githubusercontent.com/52507395/130638455-6863f301-9076-4363-9754-994fd3245c5b.png)

_Originally posted by @blaughman in https://github.com/usdoj-crt/crt-portal-management/issues/1011#issuecomment-904709767_

> Solid catch @blaughman The tiles should appear in the order in which they are listed as filters. CC @louh @billyhunt @randyabramson @ilodidoj

_Originally posted by @emilycryan in https://github.com/usdoj-crt/crt-portal-management/issues/1011#issuecomment-904711080_

I am opening a new issue to track this as the prior issue has already wrapped up.

## Suggested Actions

The fix will re-sort the order of active filters to match the current order of filters.

As discussed in group standup, we will not be pursuing a variable sorting of active filters based on last added, etc.

**Comment by blaughman** [comment] 2021-08-31 15:29
Filter labels appear to match the order of the filters above.  Moving to UAT.

**Comment by blaughman** [comment] 2021-09-01 14:53
Function works as intended in Staging.  Ready for production deploy.

**Comment by randyabramson** [comment] 2021-09-07 22:03
Works as intended on CHROME and EDGE. Closing

**Closed** 2021-09-07 22:04 UTC
Labels: Bug
