### ISSUE TITLE
Email and Phone nudge - Simplified Chinese

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#990] opened 2021-07-14 18:55 UTC
## User story:
Email and Phone nudge in Simplified Chinese.  As a public user I should be able to view the same Email and Phone nudge in Simplified Chines Language.

Refer to the following link for details and acceptance criteria.
Ref: https://github.com/usdoj-crt/crt-portal-management/issues/982

**Comment by randyabramson** [comment] 2021-07-27 01:04
@billyhunt  translation here:

[Chinese - Simplified - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881933/Chinese.-.Simplified.-.translation.-.FINAL.docx)

**Comment by blaughman** [comment] 2021-08-09 12:59
Function works as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-08-10 13:27
Works as intended. Moving to staging.

**Comment by blaughman** [comment] 2021-08-11 15:58
Verified in Production.  Closing this card.

**Closed by blaughman** 2021-08-11 15:58 UTC
