### ISSUE TITLE
Fix to trafficking modal

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1030] opened 2021-08-19 13:55 UTC
The trafficking modal's close button is not functioning. This small fix takes care of it.

**Comment by blaughman** [comment] 2021-08-23 11:54
Tested and verified in both Dev and Staging.

**Comment by randyabramson** [comment] 2021-08-24 21:15
Works as intended in CRHOME and EDGE. Nice work @billyhunt. Closing

**Closed by randyabramson** 2021-08-24 21:15 UTC
