### ISSUE TITLE
Hate Crime translation - TAGALOG

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1104] opened 2021-10-05 20:25 UTC
Translation doc:

[tagolog.docx](https://github.com/usdoj-crt/crt-portal-management/files/7289104/tagolog.docx)

**Comment by randyabramson** [comment] 2021-10-07 15:46
@louh attaching translations v2 with line breaks here
[tagologv2.docx](https://github.com/usdoj-crt/crt-portal-management/files/7305101/tagologv2.docx)

**Comment by randyabramson** [comment] 2021-10-19 17:33
Passed the GT sniff test. Moving to UAT

**Comment by blaughman** [comment] 2021-11-04 18:09
Function works as intended in Chrome, Edge and Mobile in Production.  Closing this card.

**Closed by blaughman** 2021-11-04 18:09 UTC
