### ISSUE TITLE
SPL Form Letter - Spanish

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1013] opened 2021-08-10 16:01 UTC

**Comment by blaughman** [comment] 2021-08-10 16:46
https://github.com/usdoj-crt/crt-portal-management/files/6735920/SPL.Form.Letter_SP.docx

**Comment by blaughman** [comment] 2021-08-12 15:52
Special Litigation Section removed from header.  Please use this version.
[SPL.Form.Letter_SP (3) with Header Edit.docx](https://github.com/usdoj-crt/crt-portal-management/files/6976810/SPL.Form.Letter_SP.3.with.Header.Edit.docx)

**Comment by blaughman** [comment] 2021-08-30 17:57
Function works as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment] 2021-09-01 19:12
Function works as intended in Staging.  Ready for Production deploy.

**Comment by randyabramson** [comment] 2021-09-07 21:54
Works as intended on CHROME and EDGE. Closing

**Closed** 2021-09-07 21:54 UTC
