### ISSUE TITLE
Create Rerouting Guide page

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1362] opened 2022-07-22 14:48 UTC
Using this design create the rerouting page.  

https://github.com/usdoj-crt/crt-portal-management/issues/1306

**Comment by billyhunt** [comment] 2022-07-22 17:55
@chinelo-ikejimba do you have a link to the design for this page?

**Comment by chinelo-ikejimba** [comment] 2022-07-22 20:29
@billyhunt - [Rerouting Guide | Design Handoff](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Reporting-Portal-Designs-and-Handoff?node-id=1136%3A10077)

**Comment by billyhunt** [comment] 2022-07-25 12:54
Morning @chinelo-ikejimba. Is there a way to see what is in the rest of Step 2 below the part that is visible?

**Comment by billyhunt** [comment] 2022-08-04 20:08
+ [ ] go to /admin/cts_forms/routingsection/
+ [ ] add routing sections.  The format is something like "ADM" and "Billy Hunt, Ellery Ruíz, Freddy Mercury"
+ [ ] Navigate to /form/view
+ [ ] Do a search
+ [ ] open a report
+ [ ] note the report-id and the _x_ of _y_  records next to the arrows at the top
+ [ ] click the "rerouting guide" button
+ [ ] make sure that the rerouting page looks like the page in the design
+ [ ] click the "Print" button.  Make sure the entire step 2 is visible. 
+ [ ] check to make sure your routing sections are displaying correctly in the 3rd card.
+ [ ] click the "Back to report details" button
+ [ ] make sure the report id, and _x_ of _y_ records are the same

**Comment by blaughman** [comment] 2022-08-05 12:24
Please add Richelle Porter's email address to the threatening reports area.  
[Rerouting.guide.2022.docx](https://github.com/usdoj-crt/crt-portal-management/files/9268527/Rerouting.guide.2022.docx)

**Comment by blaughman** [comment] 2022-08-08 15:24
Tests passed.  Moving to UAT.

**Comment by blaughman** [comment] 2022-08-10 14:43
Looks/functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2022-08-10 14:53
One issue noted - the Translation Request Form link does not work.  The https needs to be replaced with http since it is pointing to the old insider site.  Once that information is migrated to the Hub, the https will then work.  I will create a card for this change.

**Comment by blaughman** [comment] 2022-08-10 14:57
Card created. #1371

**Comment by blaughman** [comment] 2022-08-11 13:31
Page appears and functions as intended in Production.  Closing this card.

**Closed by blaughman** 2022-08-11 13:31 UTC
