### ISSUE TITLE
Remove bold text on hover on header links

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1123] opened 2021-10-22 20:07 UTC
This issue was created to track https://github.com/usdoj-crt/crt-portal/pull/1017 (see that PR for details) and is a spiritual follow up to #1108 (closed).

**Comment by blaughman** [comment] 2021-11-04 17:16
Function works as intended in Production.  Closing this card.

**Closed by blaughman** 2021-11-04 17:16 UTC
