### ISSUE TITLE
CSS Tweaks to Header for mobile

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1336] opened 2022-06-30 14:32 UTC
There are a couple of small changes that need to happen to the header in Mobile.  The Menu button is not correctly vertically aligned, and the Sub Title is a little too big.  See screenshot.

Currently in dev
<img width="389" alt="image" src="https://user-images.githubusercontent.com/6232068/176704342-f3fdd910-39cc-4063-ab18-130961745760.png">

What it should look like.
<img width="393" alt="image" src="https://user-images.githubusercontent.com/6232068/176704497-09c0d3dd-fa0c-4bd7-b826-c6777e1a5e8c.png">

**Comment by blaughman** [comment] 2022-07-05 16:00
Appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment] 2022-07-20 15:26
Appears as intended in Production.  Closing this card.

**Closed by blaughman** 2022-07-20 15:26 UTC
