### ISSUE TITLE
Update linking on routing-guide svg

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1368] opened 2022-08-04 20:20 UTC
There was an error in the link on the routing guide page that showed in dev, but not locally.  This PR will fix it. 

<img width="701" alt="image" src="https://user-images.githubusercontent.com/6232068/182945166-841a113c-285c-41f0-9d5a-c4ccda6d25f5.png">

**Comment by blaughman** [comment] 2022-08-10 14:44
Appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2022-08-11 13:42
Appears as intended in Production.  Closing this card.

**Closed by blaughman** 2022-08-11 13:42 UTC
