### ISSUE TITLE
Link to 'touches' report

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1148] opened 2021-11-29 16:46 UTC
We need to link to https://crt-portal-django-prod.app.cloud.gov/form/dashboard from https://crt-portal-django-prod.app.cloud.gov/form/view/ and vice versa

- [x] @randyabramson  @blaughman and Chinelo decide on link text
- [x] Chinelo provides mocks

Keep in mind that this might just be a first step as we might have more reports down the road.

**Comment by randyabramson** [comment] 2021-12-03 14:22
@chinelo-ikejimba  do you have a mock for this? If so, we can get the dev team to start their work.

**Comment by chinelo-ikejimba** [comment] 2021-12-03 20:29
@billyhunt @louh - you can access the designs in the section titled ['Global navigation'](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Aug-2021-Working-pages-(Copy)?node-id=403%3A8329)

To unify navigating between the page that shows filters and the one that shows intake specialists activity, I gave each of those pages a title to match their link labels in the recommended global navigation for the Reporting Portal.

![Reportal Portal Nav - Page 1](https://user-images.githubusercontent.com/92807659/144668177-c8b0de9c-7a85-4f2e-915d-951ddd6ae0c6.jpg)
![Reportal Portal Nav - Page 2](https://user-images.githubusercontent.com/92807659/144668179-1c36fc71-4dd5-4ca2-9af7-b879cd2caefe.jpg)
f

**Comment by blaughman** [comment] 2021-12-15 16:09
Function is working as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment] 2021-12-22 16:07
Functions as intended on Staging including keyboard navigation.  Ready for Production.

**Comment by randyabramson** [comment] 2021-12-28 22:16
Works as intended on LIVE. Good to close.

**Comment by blaughman** [comment] 2021-12-29 14:17
Functions as intended in Production.  Closing this card.

**Closed by blaughman** 2021-12-29 14:17 UTC
