### ISSUE TITLE
Hate Crime 3 - New info page for hate crime and human trafficking - ENGLISH

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1072] opened 2021-09-16 12:31 UTC
## Narrative
As a visitor to the Reporting Portal home page, when I click the Hate Crime/Human Trafficking banner on the home page to learn more, I want to see a page that gives me more detail on how I can report one of these violations

## Background
The public has  been submitting hate crime complaints since the launch of the portal.  Most of these complaints are actually not hate crimes as defined in US criminal code.  The Criminal Section spoke with the FBI and they are happy to take in hate crime reports and reach out to CRT if the situation warrants. Human Trafficking violations are also not in our jurisdiction. This ticket will add a new page with detailed info about these types of violations that users can get to by clicking the hate crimes/human trafficking banner on the homepage.

Note that Geronimo's mocks for this project are here
https://www.figma.com/file/SOICbtM64l6HJjJOR2IjvV/DOJ-CRT-Hate-Crimes-2021?node-id=2%3A2942

## Acceptance Criteria
1) Given I am on the Hate Crime/Human Trafficking info page located at https://civilrights.justice.gov/hate-crime-human-traffickng
when I look at the page
then I see a left hand navigation element that says
* How do I...
* Report a hate crime
* Report human trafficking

2) Given I am on the Hate Crime/Human Trafficking info page
when I click on the hate crime link on the left hand nav
then I move to the "Where to report a hate crime" section of the page

3) Given I am on the Hate Crime/Human Trafficking info page
when I click on the human trafficking link on the left hand nav
then I move to the "Where to report human trafficking" section of the page

4) Given I am in the "Where to report a hate crime' section of the page
when I click on the 'In cases of emergency, contact 911' link
then I get the prompt to call 911 from my computer (same function as on homepage: http://tel:911/)

when I click the 'Otherwise, contact the FBI online' link
then I go to https://www.fbi.gov/tips

when I click the 'Or a local field office by phone' link
then I go to https://www.fbi.gov/contact-us/field-offices

5) Given I am on the 'Where to report Human Trafficking' section of the page
when I click the 'Get help from the National Human Trafficking hotline' link
then I see the same modal that you see when you click on the current human trafficking modal on our form 

## Assumptions
- Use https://civilrights.justice.gov/privacy-policy as a page template
- All banner/button text will be translated into the 7 available languages if a user clicks on the various language links on the site
- We will NOT put a link to this new page in the footer just yet. It should be part of a larger Education Center down the road.
- Please disregard the back link at the top of the page

**Comment by randyabramson** [comment] 2021-09-16 12:34
Per @emilycryan 

"Hey Lodi, Imran (CRT) for the Hate Crimes page, we need to keep the pop-up that we currently use on the portal for Human Trafficking. The FBI one doesn't need it bc it's a .gov site but any non fed site requires the exit popup. So let's keep what we have on the current page and apply it to Geronimo's page when the Human Trafficking link is clicked"

**Comment by randyabramson** [comment] 2021-10-04 19:43
Blocked until we get the translations on 10/6

**Comment by blaughman** [comment] 2021-11-03 13:08
Functions as intended in Production.  Closing this ticket.

**Closed by blaughman** 2021-11-03 13:08 UTC
