### ISSUE TITLE
Auto Email Response - First Slice

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1042] opened 2021-09-01 01:06 UTC
## User story:
As a product owner, I would like to know if we can send out one Email Auto Response to a complainant with a valid Email Address based on the completion of a report submission

## Objective:
The goal of this ticket is to get a good understanding of if the GovDelivery API can communicate with the Portal and deliver an Email that is triggered by the completion of a report submission

## Key result:
Auto confirmations that include 'what to expect next' should reduce the number of repeat writer submissions

## Ticket background:
Here is the Gov Delivery TMS documentation
https://developer.govdelivery.com/api/tms/

## Acceptance criteria:

- [x] User with valid Email (that was entered into the Portal) successfully submits form on DEV server
- [x] Portal passes valid Email to Gov Delivery via TMS API
- [x] GovDelivery delivers test Email to the user

**Comment by blaughman** [comment] 2021-09-01 13:34
Once successful, card 1027 content can be applied to the messaging.

**Comment by randyabramson** [comment] 2021-09-08 17:25
Final letter from Emily here:

[Auto-reply.email-emily-final.txt](https://github.com/usdoj-crt/crt-portal-management/files/7130737/Auto-reply.email-emily-final.txt)

![auto-confirm-email-images](https://user-images.githubusercontent.com/6254621/132556009-1f663af2-a717-4203-9b98-a98ffdb764fb.png)

**Comment by billyhunt** [comment] 2021-09-08 20:09
@blaughman @randyabramson @emilycryan What do we want the email subject to be?

**Comment by emilycryan** [comment] 2021-09-08 20:10
"Thank you for submitting a report to the Civil Rights Division" would be my recc.

CC @blaughman @randyabramson @billyhunt

**Comment by randyabramson** [comment] 2021-09-08 21:16
@emilycryan I think that works. I sent myslef a note to my mobile phone with that and I was able to see up to:

"Thank you for submitting a report t", so that combined with the 'from' address should give people an idea of what it is.

cc @blaughman  @billyhunt

**Comment by billyhunt** [comment] 2021-09-09 14:53
I made a small spelling change ("WAHT" changed to "WHAT").  

Here is an updated version.

[Auto-reply.email-emily-final-2.txt](https://github.com/usdoj-crt/crt-portal-management/files/7137544/Auto-reply.email-emily-final-2.txt)

**Comment by billyhunt** [comment] 2021-09-09 14:57
Last one.  I removed an extraneous space.  

[Auto-reply.email-emily-final-3.txt](https://github.com/usdoj-crt/crt-portal-management/files/7137598/Auto-reply.email-emily-final-3.txt)

**Comment by emilycryan** [comment] 2021-09-09 14:58
Way to be a grammar nerd, @billyhunt

**Comment by blaughman** [comment] 2021-09-14 16:29
Function works as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment] 2021-09-15 15:59
Function works as intended in Staging.  Ready for Production deploy.

**Comment by blaughman** [comment] 2021-09-23 12:52
TMS logs confirm function is working in production.  Closing this card.

**Closed by blaughman** 2021-09-23 12:52 UTC
