### ISSUE TITLE
Autoresponse emails: display in intake view activity log

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1057] opened 2021-09-13 20:13 UTC
This is a followup to https://github.com/usdoj-crt/crt-portal-management/issues/1042 (merged in https://github.com/usdoj-crt/crt-portal/pull/971):

When an email response is manually sent to a complainant, the intake view's activity log will display when a response was submitted, what type of response it is, and by whom. On the other hand, when an autoresponse email is sent to a complainant after the report is first submitted, this activity does not appear in the activity log. This is because the autoresponse email is not initiated by a user, and the actstream records require an authenticated user to be attached to the action.

We do log the autoresponse email activity to server logs, and if the email is sent through TMS, there will be a record in the "TMS email" model.

The followup task here is to determine some way to show whether an autoresponse email was sent, in the report's activity log on the internal view side. An intake specialist may want to know whether an autoresponse was sent after the report was submitted, in order to inform later followup actions.

@ilodidoj, @billyhunt and I discussed a number of ways to address this:

1. Do nothing: we won't surface this activity in the activity log.
2. Create a generic "system" user to log autonomous actions in actstream.
3. Use the initial "superuser" (aka "user zero") to log autonomous actions in actstream.
4. Create a secondary log alongside actstream to log autonomous actions (no user column). Log activity will be merged in the intake view.
5. Create a new property in the TMS email records so we know when an email was sent as an autoresponse. This can then be used to create a custom activity log entry.
6. Using only existing, known information already logged, infer whether an email autoresponse was sent, and create a custom activity log entry.

While the last option appears attractive because it makes no changes to the data model or current logging infrastructure, it presents some challenges: how do we know that an email in TMS is definitely an autoresponse email? (It would need to be the first email sent for a report, and only if it was sent within a short, arbitrarily defined timeframe within the report's creation date.)

Meanwhile, we ruled out options that created new users for the actstream, from a security and compliance perspective.

The solution we'll explore first is No. 5 -- create a new property in "TMS email" that specifies the type (or trigger, reason or purpose) of the email. (The exact naming of this property is TBD.) This way, we can definitively say when a email was sent as an autoresponse, rather than inferring it. We will still need to craft a custom line item in the activity log to show this.

**Comment by blaughman** [comment] 2021-09-27 13:38
Function is working as expected.  Moving to UAT.

**Comment by blaughman** [comment] 2021-09-29 14:04
Function works as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2021-10-06 18:08
Production verified.  Closing card.

**Closed by blaughman** 2021-10-06 18:08 UTC
