### ISSUE TITLE
Modal text is red on firefox

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1118] opened 2021-10-13 20:10 UTC
The text on the contact information button is red when it is in focus on firefox.  

![image (1)](https://user-images.githubusercontent.com/6232068/137205718-45887649-862c-4645-b7d3-a7564a97dbd3.png)

**Comment by blaughman** [comment] 2021-11-04 18:11
Issue resolved.  Text appears as intended in Chrome, Edge and Mobile in Production.  Closing this card.

**Closed by blaughman** 2021-11-04 18:11 UTC
