### ISSUE TITLE
Hate Crime translation - CHINESE TRADITIONAL

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1103] opened 2021-10-05 20:24 UTC
Translation doc

[Chinese traditional.docx](https://github.com/usdoj-crt/crt-portal-management/files/7289099/Chinese.traditional.docx)

**Comment by blaughman** [comment] 2021-11-04 17:58
Function works as intended in Chrome, Edge and Mobile in Production.  Closing this card.

**Closed by blaughman** 2021-11-04 17:58 UTC
