### ISSUE TITLE
Activity Log - first slice -who touched a card and when

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1096] opened 2021-10-01 16:30 UTC
## User story:
As a division manager, I want to be able to see how many reports each member of my staff touched

## Objective:
To help division leaders help with end of the year performance

## Key result:
We hope knowing this data will help with processing efficiency

## Ticket background:
Every year, we are asked for this data by division heads. This info can also be helpful with GAO audits.

## Acceptance criteria:

1. Given that I am on the new 'activity log search' page
When I look at the page
Then I see an 'assignee' field (similar to existing assignee field), a date range picker drop down (similar to existing drop down picker) and a GO button

2. Given that I am on the new 'activity log search' page
When I click the assignee drop down
Then I see the existing type ahead field AND I can enter a name

3. Given that I am on the new 'activity log search' page
When I click the date drop down
Then I see the existing date picker form field AND I can select a date

4. Given that I am on the new 'activity log search' page
When I click the GO button
Then I see the number of reports the denoted assignee 'touched' within the selected time range

## Assumptions:
1. 'Touched' total is restricted to the number of times an assigee interacted with an aggregate of unique reports, not how many total times they interacted with individual reports,  So, if an assignee touched two reports, but they interacted with one 15 times, the result would be "2", not 17.

2. If a user enters an assignee name but not a date range (or vice versa) and tries to hit GO, no results show.
!! language

**Comment by blaughman** [comment] 2021-10-04 19:00
Need mock from Geronimo.

**Comment by geronimoramos** [comment] 2021-10-18 23:06
@blaughman @billyhunt 

UI mock for the activity log
<img width="1334" alt="Activity log UI" src="https://user-images.githubusercontent.com/49766982/137818279-2e46452e-b0ff-4fdc-85a6-6ca7f22806a1.png">
t

**Comment by randyabramson** [comment] 2021-10-19 02:15
@geronimoramos  looks good! 

Three comments:

1. I am not sure we need the drop down on the top right (drop down label)
2. I don't think we need the check box to the left of 'assignee'
3. At this point, I am not sure we will allow for selecting more than one assignee at one time, so I am not sure we need the pagination

At some point we should think about a title for this page -- maybe 'Assignee Activity' or the like; also, we should think about a navigation link back to the 'View All Table' (these are both 'nice to haves', Geronimo...I know I am just adding them now).

**Comment by ilodidoj** [comment] 2021-11-04 01:43
@billyhunt dev is filtering via id number instead of the user login name.  It should filter as https://crt-portal-django-dev.app.cloud.gov/form/dashboard/?assigned_to=bill.Laughman instead of https://crt-portal-django-dev.app.cloud.gov/form/dashboard/?assigned_to=3.  Please create another card to change filter from id name instead of number, which does not return correct count for the user aka assigned to name selected.

**Comment by blaughman** [comment] 2021-11-08 15:43
Function works as expected in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-11-10 20:46
Stage url is https://crt-portal-django-stage.app.cloud.gov/form/dashboard/

**Comment by blaughman** [comment] 2021-11-10 20:46
Functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2021-11-17 15:13
Report functions as intended in Production.  Closing this card.

**Closed by blaughman** 2021-11-17 15:13 UTC
