### ISSUE TITLE
Translate and update banner text.

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1050] opened 2021-09-08 13:58 UTC
As recommended by USWDS 2.8.0 (see https://github.com/usdoj-crt/crt-portal-management/issues/1041 for more details on the upgrade process), the text on the banner at the top of the site has been updated.

Our current banner text reads:

<img width="1094" alt="Screen Shot 2021-08-26 at 12 59 28 PM" src="https://user-images.githubusercontent.com/2553268/131004729-6e028f37-f68f-4fa3-ba48-d4a33a2ff585.png">

The new text will look like this:

<img width="1077" alt="Screen Shot 2021-08-26 at 1 04 04 PM" src="https://user-images.githubusercontent.com/2553268/131005279-520a3437-f263-48c5-8975-366448c4f08b.png">

The USWDS team recommends that projects update this text as soon as possible. This will also bring our banner up to date with banners used elsewhere in the federal website ecosystem. (The front page of the [DOJ website](https://www.justice.gov/) for example, uses the updated text.)

USWDS provides both English and Spanish translations, but we will need to translate the text to other languages that we support: Chinese (both traditional and simplified), Vietnamese, Korean, and Tagalog.

---

Here is the updated English text to translate:

> **Official websites use .gov**
> A **.gov** website belongs to an official government organization in the United States. 

> **Secure .gov websites use HTTPS**
> A **lock (🔒)** or **https://** means you’ve safely connected to the .gov website. Share sensitive information only on official, secure websites. 

Please take note of where the **bold** text is. The second text uses a lock icon which we will programmatically replace with the correct image in our templates, but in order to make it easier to pass the text around I'm using a lock emoji in its place.

**Comment by blaughman** [comment] 2022-02-01 15:41
Spanish Translation
[Landing Page Updates - Spanish + MC 2022 01 31.docx](https://github.com/usdoj-crt/crt-portal-management/files/7979741/Landing.Page.Updates.-.Spanish.%2B.MC.2022.01.31.docx)

**Comment by louh** [comment] 2022-02-04 15:17
Remainder of translations are linked on #1114.

**Comment by blaughman** [comment] 2022-02-09 18:42
Banner text appears as intended in all languages.  Moving to UAT.

**Comment by blaughman** [comment] 2022-02-16 21:02
Banner text appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2022-02-23 15:23
Banner appears as intended in Production.  Closing this card.

**Closed by blaughman** 2022-02-23 15:23 UTC
