### ISSUE TITLE
Intake search filters: make active filter labels more consistent with filter UI

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1037] opened 2021-08-24 19:39 UTC
## Summary

As originally posted in https://github.com/usdoj-crt/crt-portal-management/issues/1011#issuecomment-904764972, the active filter "pills" have inconsistent labeling with the filter input UI:

<img width="1210" alt="Screen Shot 2021-08-24 at 11 41 08 AM" src="https://user-images.githubusercontent.com/2553268/130648524-f942c12e-2473-494b-b245-04428cba4410.png">

- [x] "ID" and "Complaint ID" - inconsistent label text
- [x] "create date start" and "create date end" - inconsistent capitalization
- [x] "Servicemember" and "Service member" - inconsistent word spacing
- [x] "correctional facility type" and "Prison Type" - inconsistent label text
- [x] "Summary" and "CRT Summary" - inconsistent label text
- [x] "Location name" and "Incident location" - inconsistent label text

This is broken out as a separate task for further consideration because active filters read their labels from the model. Making changes to what the active filters display is not as easy as updating the templates for form labels.

@emilycryan also noted during standup that "Servicemember" (one word) is the proper term, not the two-word "Service member."

**Comment by blaughman** [comment] 2021-09-01 18:58
Function works as intended in Dev. Moving to UAT.

**Comment by blaughman** [comment] 2021-09-01 19:08
Function works as intended in Staging.  Ready for Production deploy.

**Comment by randyabramson** [comment] 2021-09-07 22:08
Works as intended on CHROME and EDGE. Nice work @louh. Closing

**Closed by randyabramson** 2021-09-07 22:08 UTC
