### ISSUE TITLE
Hate Crime translation - VIETNAMESE

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1105] opened 2021-10-05 20:26 UTC
Tanslation doc

[vietnamese.docx](https://github.com/usdoj-crt/crt-portal-management/files/7289111/vietnamese.docx)

**Comment by blaughman** [comment] 2021-11-04 18:01
Function works as intended in Chrome, Edge and Mobile in Production.  Closing this card.

**Closed by blaughman** 2021-11-04 18:01 UTC
