### ISSUE TITLE
Hate Crime Translation - SPANISH

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1110] opened 2021-10-12 11:15 UTC
@louh attaching translations v2 with line breaks here
[Hate Crimes Spanish Translation Request SPA Final 2021 10 08.docx](https://github.com/usdoj-crt/crt-portal-management/files/7329402/Hate.Crimes.Spanish.Translation.Request.SPA.Final.2021.10.08.docx)

**Comment by randyabramson** [comment] 2021-10-19 17:32
Passed the GT sniff test. Moving to UAT

**Comment by blaughman** [comment] 2021-11-04 17:57
Function works as intended intended in Chrome, Edge and Mobile.  Closing this card.

**Closed by blaughman** 2021-11-04 17:57 UTC
