### ISSUE TITLE
Create sticky sidebar.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1208] opened 2022-02-22 16:39 UTC
The sidebar on certain pages links to anchors that extend well past the sidebar itself, which can lead to a bad user experience.  We should have the sidebar travel with the scrolling page in those instances.  

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/6232068/155177626-28e99dd8-74f5-4bb2-b69d-385f45f4780c.png">

**Comment by blaughman** [comment] 2022-03-28 18:50
Functions as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2022-03-31 11:11
Works as inteded on staging

**Comment by blaughman** [comment] 2022-03-31 19:18
Functions as intended in Staging.  Ready for Production.

**Comment by randyabramson** [comment] 2022-04-20 10:30
Functions as expected on live server.

**Comment by blaughman** [comment] 2022-04-20 12:54
Functions as intended in Production.  Closing this card.

**Closed by blaughman** 2022-04-20 12:54 UTC
