### ISSUE TITLE
"Edit this page" at end of complaint form doesn't lead to the right section

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1121] opened 2021-10-21 17:45 UTC
## Summary

With the hate crime/human trafficking question removed, the "Edit this page" button at the review step of the complaint form no longer goes to the right section in some instances.

- Contact -> Contact (as expected)
- Primary concern -> Primary concern (as expected)
- Location -> form submittal (**incorrect**)
- Personal characteristics -> Date (**incorrect**)
- Date -> Personal description (**incorrect**)
- Personal description -> Review your report (**incorrect**)

It seems the previous behavior may have also had a small bug, as clicking on "Edit this page" from the Location section when it wasn't a workplace, school, etc, would lead to the Hate crime/Human trafficking question as well.

### Steps To Reproduce

1. Fill out a report
2. On the "review your report" step, scroll down and click "Edit this page" on various sections.

### Expected Behavior

"Edit this page" should go to the correct section.

### Actual Behavior

It doesn't. (See above)

## Suggested Actions

There may be two separate issues happening here.

1. The easier one to tackle is that the steps after location are now off by one because of the removal of a step. This can be renumbered.
2. The harder one to understand right now is that each type of location question is an individual step that is conditionally determined. Rather than going to the wrong section, some conditional check is failing and it's defaulting to submitting the form.

## Acceptance Criteria

- Update form steps
- Add a "Edit this page" step to confirm it's doing the right thing in the E2E test.

**Comment by ilodidoj** [comment] 2021-10-21 19:30
@louh our pa11y test or E2E test have some clue on this. Every time when we change or remove a page/steps or move up and down options, we probably have to also check the JavaScript associated that calling the page.  Element tag or ID get reordered due to these changes.

**Comment by blaughman** [comment] 2021-11-04 18:22
Functions as intended in Chrome, Edge and Mobile in Production.  Closing this card.

**Closed by blaughman** 2021-11-04 18:22 UTC
Labels: Bug
