### ISSUE TITLE
Proform created report created 4 duplicates

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#984] opened 2021-07-02 14:46 UTC
## Summary

Intake specialist created [this report](https://crt-portal-django-prod.app.cloud.gov/form/view/83473/?next=%3Fper_page%3D15%26assigned_section%3DADM%26assigned_section%3DAPP%26assigned_section%3DCRM%26assigned_section%3DDRS%26assigned_section%3DELS%26assigned_section%3DEOS%26assigned_section%3DFCS%26assigned_section%3DHCE%26assigned_section%3DIER%26assigned_section%3DSPL%26assigned_section%3DVOT%26contact_email%3Dbiddle.karla%40gmail.com%26page%3D1&index=0) using the Pro Form. When she checked back, duplicate reports were created, all submitted at 9:07 AM ET.

More detail from the complainant: "I created the record from an email.  It was a long email, over 500 characters.  I created the record, saved it and then had to add the rest of the email into the Activity field.  After I saved that, I saw that the complainant had 5 entries.  I had already checked to see if they were in the portal so there shouldn’t have been any additional records.  Only the first one has the rest of the email in the Activity field."

### Steps To Reproduce

1. First step to reproduce
2. Next step
3. (etc.)

If it's relevant, add browser or operating system where the error occurs.

**Comment by randyabramson** [comment] 2021-07-13 16:09
@billyhunt able to recreate by clicking the submit button multiple times

**Comment by randyabramson** [comment] 2021-07-13 16:12
@emilycryan  suggests that we disable the submit button after submission

**Comment by blaughman** [comment] 2021-07-21 13:14
When testing, I created a record in the proform and clicked 'submit' as quickly as I could.  18 records were created before the initial request was processed.  I thought the 'submit' button was to be disabled after the user clicked it the first time?

**Comment by blaughman** [comment] 2021-07-22 13:40
Function works as intended.  Create card for issue discovered during testing - repeatedly clicking submit on the proform will create duplicate records before the initial request is processed.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-07-27 20:47
Cannot test without creating new records on live production. Moving to closed.

**Closed** 2021-07-27 20:47 UTC
Labels: Bug
