### ISSUE TITLE
Replace touchpoints form on Submission page

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1369] opened 2022-08-05 20:37 UTC
**Background:**

We replace the generic 'tell us how to improve this site' touchpoints form on the Portal submission page with a recruitment form for user testing.

I believe that recruitment campaign is over, and we'd like to switch back to the generic form.

**More detail:**
The instructions to surface the touchpoints functionality is as follows, but please let me know if there's another variable you need:

**Touchpoints-hosted URL**
Every form gets a touchpoints-hosted URL.
This form can be publicly accessed from the following URL. You can choose to share this URL with users, or not.

https://touchpoints.app.cloud.gov/touchpoints/a24aeb5e/submit

**Delivery options**
Add the following markup to your site as a place to display the Touchpoint modal.

<div id=""></div>

**Add the following script to your site to embed your form.**

<script src="https://touchpoints.app.cloud.gov/touchpoints/a24aeb5e.js" async></script>

**Comment by blaughman** [comment] 2022-08-17 12:08
The touchpoints form appears as intended.  Moving to UAT.

**Comment by blaughman** [comment] 2022-08-19 14:00
Functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2022-08-24 14:09
Deployed to Production, but can't test without creating a false record.  Closing this card.

**Closed by blaughman** 2022-08-24 14:09 UTC
