### ISSUE TITLE
Hate Crime translation - KOREAN

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1106] opened 2021-10-05 20:27 UTC
Translation doc

[korean.docx](https://github.com/usdoj-crt/crt-portal-management/files/7289118/korean.docx)

**Comment by louh** [comment] 2021-10-06 19:20
@randyabramson The Korean translator has noted in their responses that “How do I…” as a heading doesn’t make sense in Korean word order. “How do I” in Korean would occur at the end of sentences, not at the beginning. How should we address this?

**Comment by randyabramson** [comment] 2021-10-07 15:47
@louh attaching translations v2 with line breaks here

[koreanv2.docx](https://github.com/usdoj-crt/crt-portal-management/files/7305110/koreanv2.docx)

**Comment by blaughman** [comment] 2021-11-04 18:07
Function works as intended in Chrome, Edge and Mobile in Production.  Closing this card.

**Closed by blaughman** 2021-11-04 18:07 UTC
