### ISSUE TITLE
Translation and clearance for changing 'location name' to 'organization name'

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1094] opened 2021-09-30 13:33 UTC
@blaughman There's some agreement to change 'location name' to 'organization name'. but since Geronimo is coming on, let's ask him about some light weight testing we can do around this to 'sanity check' it. Maybe do it with CRT employees that might not be familiar with the form.

Some steps:

- [x] Need translation
- [x] Sanity check language change with Geronimo
- [x] Double check with KIlain on language change
- [x] If passed sanity check, get translations for 'organization name'

**Comment by blaughman** [comment] 2022-01-03 17:43
@randyabramson @louh @ilodidoj @billyhunt Spanish translation is attached   
[12.23.21 Translation Request - Spanish.docx](https://github.com/usdoj-crt/crt-portal-management/files/7803263/12.23.21.Translation.Request.-.Spanish.docx)

**Comment by blaughman** [comment] 2022-01-12 17:36
This update will occur on Step 3 of the public facing form

![image](https://user-images.githubusercontent.com/52507395/149192350-f289b254-f795-46e1-9eda-e95e948e6cdb.png)

**Comment by louh** [comment] 2022-01-12 18:39
@blaughman are we also changing the same label on the report view?

<img width="603" alt="Screen Shot 2022-01-12 at 1 38 04 PM" src="https://user-images.githubusercontent.com/2553268/149201699-702a7823-65dc-4b08-a303-3399868c006a.png">

**Comment by blaughman** [comment] 2022-01-12 18:46
@louh Good catch.  You are correct.

**Comment by blaughman** [comment] 2022-01-18 18:30
Change appears as intended on both front end and back end on Dev.  Moving to UAT.

**Comment by blaughman** [comment] 2022-01-20 20:46
Change appears as intended in all languages on the front end and on the back end in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2022-01-26 14:51
Appears as expected in Production.  Closing this card.

**Closed by blaughman** 2022-01-26 14:51 UTC
