### ISSUE TITLE
Response Template - Hide templates no longer in use

### ISSUE THREAD

**Issue by kewitham** [usdoj-crt/crt-portal-management#1460] opened 2023-01-30 18:58 UTC
## User story:
Currently when a response template is removed the manage actions do not delete it from the database (only create and update) so it has to be manually removed in the admin console. We want to automate this process while keeping any user created or migrated response templates from getting deleted.

## Objective:
Automate deletion process for response templates removed from the /response_templates/ folder

## Ticket background:
This ticket is an offshoot of the [1452](https://github.com/usdoj-crt/crt-portal-management/issues/1452) updates to the response templates.

**Comment by kewitham** [comment] 2023-02-01 20:41
Updated per discussion in stand up - prefer to hide templates rather than delete them

**Comment by blaughman** [comment] 2023-02-07 18:44
@kewitham We're only hiding the letters in Production, correct?

**Comment by kewitham** [comment] 2023-02-07 20:38
@blaughman we are hiding the templates in the dropdown on the report detail page but they will still be accessible in the admin console (on dev and prod).

**Comment by blaughman** [comment] 2023-02-08 18:06
Function works as expected in Dev.  Moving to UAT complete.

**Comment by blaughman** [comment] 2023-02-21 15:48
Functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2023-02-21 20:32
Feature functions as intended in Production.  Closing this card.

**Closed by blaughman** 2023-02-21 20:32 UTC
