### ISSUE TITLE
Email allow list should be case insensitive

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1052] opened 2021-09-09 13:48 UTC
The email allow list used on dev and staging is currently case sensitive.  This can cause confusion.  For example, if you submit a report as "William.Hunt@usdoj.gov" it will not be allowed because in the list, it is "william.hunt@usdoj.gov".

**Comment by blaughman** [comment] 2021-09-14 18:24
Function works as intended for email addresses with both lower and upper case letters.  Moving to UAT.

**Closed** 2021-09-20 19:06 UTC
