### ISSUE TITLE
Long text in page header (e.g. Tagalog) breaks with undesirable line-height

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1127] opened 2021-10-27 20:23 UTC
via @randyabramson, originally posted in #1104:

> I noticed one small spacing issue on the headline on MOBILE (iphone, Safari) only on Staging.. Works fine on other languages. 

![tagalog-mobile](https://user-images.githubusercontent.com/6254621/139082742-72a0afd8-b747-4707-9f2d-d9419c44da3b.png)

Although this is present on the hate-crime/human-trafficking page, this was not originally caused by that work. (The bug is present on the current production site.) The fix would require adjusting the line-height of the header to be at a readable height when it breaks, but ensuring that the look of the header remains in accordance with previous design conversations.

**Comment by blaughman** [comment] 2021-11-04 17:54
Text appears as intended on Production - mobile.  Closing this card.

**Closed by blaughman** 2021-11-04 17:54 UTC
Labels: Bug
