### ISSUE TITLE
SPL Form Letter - Simplified Chinese

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1015] opened 2021-08-10 16:41 UTC

**Comment by blaughman** [comment] 2021-08-18 18:17
[1368276.SPL.Chinese-Simplified.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7009302/1368276.SPL.Chinese-Simplified.final.docx)

FBI approved version

**Comment by blaughman** [comment] 2021-09-01 19:03
Function appears as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-09-07 22:43
Worked as intended on CHROME and EDGE. Closing

**Closed by randyabramson** 2021-09-07 22:43 UTC
