### ISSUE TITLE
Email and Phone nudge - Espanol

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#989] opened 2021-07-14 18:53 UTC
## User story:
As a public user I should be able to view the same Email and Phone nudge in Spanish Language.

Refer to the following link for details and acceptance criteria.
Ref: https://github.com/usdoj-crt/crt-portal-management/issues/982

**Comment by randyabramson** [comment] 2021-07-27 01:04
@billyhunt  translation here:

[Spanish - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881937/Spanish.-.translation.-.FINAL.docx)

**Comment by ilodidoj** [comment] 2021-08-02 18:49
@randyabramson @blaughman It seems English to all language translations has a different format presentation than the English mock for this button: "**No, I don't want to provide it**" .  All other language version has this as "No, I **do not** want to provide it". Meaning is same, just the format presentation is different in all languages compare to English format of the button.

**Comment by randyabramson** [comment] 2021-08-10 13:36
Works as intended...moving to staging.

**Comment by blaughman** [comment] 2021-08-11 15:59
Verified in Production.  Closing this card.

**Closed by blaughman** 2021-08-11 15:59 UTC
