### ISSUE TITLE
Convert images to PNG

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1211] opened 2022-02-28 20:28 UTC
@chinelo-ikejimba 

If you get a moment, can you please convert these 2 images to PNG format so they will render correctly in the GMAIL client?

* https://cg-b2626a97-5c90-4d35-a39b-24f3b035d5c9.s3-us-gov-west-1.amazonaws.com/static/img/phone_70.svg

* https://cg-b2626a97-5c90-4d35-a39b-24f3b035d5c9.s3-us-gov-west-1.amazonaws.com/static/img/mail_70.svg

Thank you!

**Comment by chinelo-ikejimba** [comment] 2022-03-01 21:08
@randyabramson here you go. Let me know if you have any issues with how they render (size, pixelation, etc.).

![mail_70](https://user-images.githubusercontent.com/92807659/156248929-53138d13-1e92-4df2-b013-b70ee6f8708d.png) 

![phone_70](https://user-images.githubusercontent.com/92807659/156248930-5116bf3c-9716-43be-bed6-7781cd9a9839.png)

**Comment by randyabramson** [comment] 2022-03-01 21:30
@billyhunt or @blaughman  - please replace the above pngs for the svg files in the Housing form letter at https://github.com/usdoj-crt/crt-portal-management/issues/1112

Thank you!

**Comment by blaughman** [comment] 2022-03-09 19:47
@billyhunt @ilodidoj @chinelo-ikejimba @randyabramson I tested this in both Outlook and gmail.  Results are below:
Gmail:
![image](https://user-images.githubusercontent.com/52507395/157521784-646438b0-54ff-428a-a43d-12ca3a0e7820.png)
Outlook:
![image](https://user-images.githubusercontent.com/52507395/157521889-4619abd2-84df-45e9-8c8d-30d5cfb36557.png)

**Comment by blaughman** [comment] 2022-03-09 19:47
I'm not sure why the mail icon isn't showing on gmail.  Thoughts?

**Comment by billyhunt** [comment] 2022-03-09 19:49
You want to pair and we can look at it together?

**Comment by blaughman** [comment] 2022-03-09 20:05
Cache issue resolved.  Appears as intended in Gmail.  Moving to UAT.

**Comment by blaughman** [comment] 2022-03-23 13:55
Closing this card.  Can't be tested without creating a fake record.

**Closed by blaughman** 2022-03-23 13:55 UTC
