### ISSUE TITLE
Users unable to un-assign Reports

### ISSUE THREAD

**Issue by Jkrzy** [usdoj-crt/crt-portal-management#739] opened 2020-10-09 18:42 UTC
In #737 we received a report of user's being unable to select an `empty` or `null` value for the `Assigned to` field and remove the current assignee from a Report.

@Jkrzy took an initial look:
>This looks to be rooted in how we're using accessible-autocomplete, specifically we're providing no way for a user to select a null value or otherwise remove a current assignee. This isn't an area we've touched in the last ~6 months, I suspect this has always been the behavior since initial implementation.
>https://github.com/alphagov/accessible-autocomplete#null-options

We'll know we're done when:
- [ ] We've decided how/if a User should be able to un-assign a Report
- [ ] We've implemented any necessary functionality to allow users to un-assign.

**Comment by blaughman** [comment] 2021-11-12 18:45
Function works in Dev as expected.  Moving to UAT.

**Comment by blaughman** [comment] 2021-11-29 16:45
Functions as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2021-12-01 13:53
Functions as intended in Production.  Closing this card.

**Closed by blaughman** 2021-12-01 13:53 UTC
Labels: Bug
