### ISSUE TITLE
Date picker bug on intake view

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1085] opened 2021-09-27 22:10 UTC
## Summary

On the `/form/view/` page, there's a console error:

<img width="472" alt="Screen Shot 2021-09-28 at 11 44 56 AM" src="https://user-images.githubusercontent.com/2553268/135121584-0313c840-5edc-494d-95d7-0dd62ddd9f99.png">

This causes the second date range picker to look wrong.

### Steps To Reproduce

Go to the `/form/view/` page and click on the submission date filter dropdown.

### Expected Behavior

Date picker looks like this:

<img width="283" alt="Screen Shot 2021-09-28 at 11 48 50 AM" src="https://user-images.githubusercontent.com/2553268/135121468-22836b3f-66bd-4592-9fd0-fa8dc7f8d29c.png">

### Actual Behavior

Date picker elements are misplaced and the second date picker has the wrong styling.

<img width="278" alt="Screen Shot 2021-09-28 at 11 46 02 AM" src="https://user-images.githubusercontent.com/2553268/135121485-ab8337d8-1a76-4151-8073-0c1958b1fc27.png">

## Suggested Actions

This may have been introduced in changes to JavaScript between USWDS@2.0.3 and 2.8.1.

## Acceptance Criteria

Submission date dropdown should return to normal.

**Comment by blaughman** [comment] 2021-09-29 13:51
Function works as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-10-13 10:24
Works as intended on Staging in Chrome and EDGE

**Comment by randyabramson** [comment] 2021-10-19 21:10
tested in production on EDGE and CHROME - works as expected. Feel free to close.

**Closed** 2021-10-20 14:35 UTC
Labels: Bug
