### ISSUE TITLE
Move page-errors html from report_base to report

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1174] opened 2022-01-05 20:23 UTC
Currently page-errors messaging is located in report_base, which was fine until we started using field validation on the pro form.  To make it work currently, I had a brittle solution.  To make the code more robust, I would like to move the page-error logic from report_base into the standard report.  

Current CSS which is brittle. 
```
//Since #page-errors is in a parent report_base.html, and we don't want it in the pro form, we reference it via the #id_pro_form_view-current_step sibling.
#id_pro_form_view-current_step ~ .crt-portal-card {
  #page-errors {
    display: none;
  }
}
```

**Comment by blaughman** [comment] 2022-01-31 15:56
Errors displayed as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment] 2022-02-04 14:37
Functions as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2022-02-09 16:02
Production is displaying errors as expected.  Closing this card.

**Closed by blaughman** 2022-02-09 16:02 UTC
