### ISSUE TITLE
Header logo should provide navigation to homepage

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1100] opened 2021-10-04 20:29 UTC
Geronimo notes that the logo on the header for subpages (like https://civilrights.justice.gov/privacy-policy) should provide navigation to the landing page. (The heading on the left side)

<img width="1380" alt="Screen Shot 2021-10-04 at 4 30 12 PM" src="https://user-images.githubusercontent.com/2553268/135920402-5f86affd-83a6-44aa-878a-26d97d68846a.png">

This is pretty common for websites, and it also helps address the "back button or breadcrumb" problem (where neither solution had felt right when we discussed them). Making the heading element navigable gives the user an easier path back to the landing page in an intuitive way.

**Comment by blaughman** [comment] 2021-10-19 18:23
Function works as intended in Chrome, Edge and mobile.  Moving to UAT.

**Comment by blaughman** [comment] 2021-11-03 13:13
Function works as intended in Production.  Closing this ticket.

**Closed by blaughman** 2021-11-03 13:13 UTC
Labels: Enhancement
