### ISSUE TITLE
Need update to translation on confirmation page.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1325] opened 2022-06-27 17:48 UTC
On the confirmation page, I noticed that we are missing a translation.  

<img width="757" alt="image" src="https://user-images.githubusercontent.com/6232068/176003946-eb03925f-63c6-4d3b-b56c-9bb0abadaa87.png">

(note the American Bar Association bullet is in english)

This is across at least two languages.

**Comment by billyhunt** [comment] 2022-07-06 20:46
In working on these translations, I found another broken link in Spanish language version of the confirmation page.  I think we might want to up the priority on automated broken link checking.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/6232068/177639883-34a75bd6-83f5-49e9-bae8-b7d6a555cfa8.png">

**Comment by blaughman** [comment] 2022-07-08 18:53
Translations appear as intended.  Moving to UAT.

**Comment by blaughman** [comment] 2022-07-27 15:01
Can't test this without creating a bad record in Production.  Closing this card since it works in Staging.

**Closed by blaughman** 2022-07-27 15:01 UTC
