### ISSUE TITLE
Hate Crime translation - CHINESE SIMPLIFIED

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1102] opened 2021-10-05 20:23 UTC
Translation doc:

[Chinese simplified.docx](https://github.com/usdoj-crt/crt-portal-management/files/7289090/Chinese.simplified.docx)

**Comment by randyabramson** [comment] 2021-10-07 15:46
@louh attaching translations v2 with line breaks here

[Chinese simplifiedv2.docx](https://github.com/usdoj-crt/crt-portal-management/files/7305097/Chinese.simplifiedv2.docx)

**Comment by blaughman** [comment] 2021-11-04 17:59
Function works as intended in Chrome, Edge and Mobile in Production.  Closing this card.

**Closed by blaughman** 2021-11-04 17:59 UTC
