### ISSUE TITLE
Hate Crime 2 - home page info bar (need transaltions too)

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1071] opened 2021-09-16 12:30 UTC
## Narrative
As a visitor to the Reporting Portal home page, I want to learn about the best way to report a human trafficking or hate crime violation.

## Background
The public has  been submitting hate crime complaints since the launch of the portal.  Most of these complaints are actually not hate crimes as defined in US criminal code.  The Criminal Section spoke with the FBI and they are happy to take in hate crime reports and reach out to CRT if the situation warrants. Human Trafficking violations are also not in our jurisdiction. This ticket will add a banner that links to a page with more Hate Crime and Human trafficking instruction.

## Acceptance Criteria
1) Given I am on the home page of civilrights.justice.gov
when I look at the page
then I see a thin yellow banner and Get Help NOW! button under the blue/white nav bar

2) Given I am on the home page of civilrights.justice.gov
when click the Get Help Now! button
then I go to a page that explains how I can report hate crimes or trafficking violations

## Assumptions
- Banner and button are visible on mobile, tablet and desktops
- All banner/button text will be translated into the 7 available languages if a user clicks on the various language links on the site

**Comment by randyabramson** [comment] 2021-09-17 14:34
Blocked until we have translations for the banner and button.

@randyabramson to supppy Geronimo mock

**Comment by randyabramson** [comment] 2021-10-18 14:09
Works as expected on Chrome, EDGE and iPhone Mobile. Moving to UAT Complete.

**Comment by randyabramson** [comment] 2021-10-18 14:09
Works as expected on Chrome, EDGE and iPhone Mobile. Moving to UAT Complete.

**Comment by blaughman** [comment] 2021-11-03 13:08
Functions as intended in Production.  Closing this ticket.

**Closed by blaughman** 2021-11-03 13:08 UTC
