### ISSUE TITLE
IER form letter

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1043] opened 2021-09-01 01:25 UTC
- [x] Bill getting letter approved from Jenny
- [x] Get IER letter translated

**Comment by randyabramson** [comment] 2021-09-14 15:45
Moving this to sprint 54

**Comment by louh** [comment] 2021-12-01 15:58
@randyabramson @blaughman Is there an English language IER form letter?

**Comment by blaughman** [comment] 2021-12-01 16:02
@louh Sorry, I thought this was in the card.
[Draft IER referral response for portal.docx](https://github.com/usdoj-crt/crt-portal-management/files/7635390/Draft.IER.referral.response.for.portal.docx)

**Comment by blaughman** [comment] 2021-12-01 21:01
Name for dropdown menu:
IER - Form Letter 

Re: line should be consistent with other form letters
Response: Your Civil Rights Division Report - [complaint ID] from the Immigrant and Employee Rights Section

**Comment by blaughman** [comment] 2021-12-07 18:48
Letter appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment] 2021-12-09 15:56
Letter appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment] 2021-12-15 16:11
Letter appears as intended in Production.  Closing this card.

**Closed by blaughman** 2021-12-15 16:11 UTC
