### ISSUE TITLE
SPL Form Letter - Vietnamese

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1016] opened 2021-08-10 16:42 UTC

**Comment by blaughman** [comment] 2021-08-18 18:19
[1368288.SPL.Vietnamese.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7009311/1368288.SPL.Vietnamese.final.docx)

FBI approved version

**Comment by blaughman** [comment] 2021-09-02 14:29
Function works as intended in Staging.  Ready for Production.

**Comment by randyabramson** [comment] 2021-09-07 22:40
Works as intended in CHROME and DEV. Closing

**Closed by randyabramson** 2021-09-07 22:40 UTC
