### ISSUE TITLE
Intake search filters: make "location name" labels more consistent in UI

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1036] opened 2021-08-24 19:28 UTC
## Summary

On the intake search filter page, the label "Incident location" is used in two places to label different things. In the filters, "incident location" is a free-form text field for the location name. In the table below, "incident location" is the label for city/state. (Originally reported in https://github.com/usdoj-crt/crt-portal-management/issues/1011#issuecomment-904764972)

![Screenshot 2021-08-24 at 11-42-50 Contact the Civil Rights Division Department of Justice](https://user-images.githubusercontent.com/2553268/130647972-a6fdf075-4c64-4c82-b11f-05825883e565.png)

Additionally:

> The dropdown on the "Incident city/state" has two labels: "Incident location city" and "Location state". I think the inconsistent labels makes my eye twitch just a little. Could we standardize to use the same phrasing? e.g. update "Location state" to "Incident location state", or better yet, simplify both to "City" and "State" (which is what the filter pills use, see screenshot below)

<img width="336" alt="Screen Shot 2021-08-24 at 11 45 36 AM" src="https://user-images.githubusercontent.com/2553268/130648058-fcf781ce-7c23-4a1a-a43b-f8dfd26b5035.png">

## Suggested Actions

Following up from our team stand-up, the following recommendations were made:

- We need to keep "Incident City/State" and "Incident Location" the same; users expect "Incident" in the filter name to clarify the distinction between where an incident occurred and where a reporter came from.
- The "Incident Location" text input placeholder can say "Incident Location Name" to clarify that it is a name, not a city/state pair. (However, this change would eventually be superceded if the text inputs are consolidated.)
- In the table, change "Location Name" to read "Incident Location". It can't say "Incident Location Name" or it will split onto three lines, and we should keep the heading at two lines.
- In the table, change "Incident Location" to react "Incident City/State" to match the dropdown filter label.
- In the city/state dropdown, change "Incident location city" to "Incident city"
- In the city/state dropdown, change "Location state" to "Incident state"

@emilycryan Let me know if I'm missing anything!

**Comment by emilycryan** [comment] 2021-08-25 16:56
@louh Looks 💯  Perfect - thank you!

**Comment by blaughman** [comment] 2021-08-31 15:30
Labels are consistent with filters.  Moving to UAT.

**Comment by blaughman** [comment] 2021-09-01 14:52
Function works as intended in Staging.  Ready for production deploy.

**Comment by randyabramson** [comment] 2021-09-07 21:59
Works as expected in CHROME and EDGE. Nice work @louh. Closing this.

**Closed** 2021-09-07 22:01 UTC
Labels: Enhancement
