### ISSUE TITLE
Email and Phone nudge - Traditional Chinese

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#991] opened 2021-07-14 18:57 UTC
## User story:
Email and Phone nudge in Traditional Chinese.  As a public user I should be able to view the same Email and Phone nudge in Simplified Chines Language.

Refer to the following link for details and acceptance criteria.
Ref: https://github.com/usdoj-crt/crt-portal-management/issues/982

**Comment by randyabramson** [comment] 2021-07-27 01:05
@billyhunt  translation here:

[Chinese - Traditional - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881938/Chinese.-.Traditional.-.translation.-.FINAL.docx)

**Comment by blaughman** [comment] 2021-08-03 19:42
Function works as intended.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-08-10 13:26
Works as intended. Moving to staging.

**Comment by blaughman** [comment] 2021-08-11 16:01
Verified in Production.  Closing this card.

**Closed by blaughman** 2021-08-11 16:01 UTC
